[tool.poetry]
name = "space-rocks"
version = "0.1.0"
description = "for space-rocks"
authors = ["Max Mahlke <max.mahlke@oca.eu>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.4"
pandas = "^1.2.1"

[tool.poetry.dev-dependencies]
sphinx-redactor-theme = "^0.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
